@echo off
echo Starting Second Brain Services...
echo.

echo Starting Frontend...
start "Frontend" cmd /k "cd Frontend && npm run dev"

echo Starting Backend...
start "Backend" cmd /k "cd Backend && npm run dev"

echo Starting Voice To Text Server...
start "VoiceToTextServer" cmd /k "cd VoiceToTextServer && start.bat"

echo Starting AI Service...
start "AI Service" cmd /k "cd ../Second Brain API 2/ai_service && python manage.py runserver"

echo Starting WebSocket Server...
start "WebSocket Server" cmd /k "cd ../Second Brain API 2/Chat && python WebSocketServer.py"

echo.
echo All services are starting in separate windows...
echo.
pause
